name: Build and Push Binaries

on:
  push:
    branches:
      - binaries-source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Binaries-Source
        uses: actions/checkout@v3
        with:
          path: src
          ref: binaries-source
          token: ${{ secrets.PAT }}

      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          path: dst
          ref: main
          token: ${{ secrets.PAT }}

      - name: Remove Old Content From Main
        shell: bash
        working-directory: dst
        run: |
          folders_to_remove=("cgal")
          for folder in "${folders_to_remove[@]}"; do
            if [ -d "$folder" ]; then
              rm -rf "$folder"
            fi
          done

      - name: Init Submodules
        working-directory: src
        run: |
          git submodule update --init --recursive

      - name: Build CGAL
        working-directory: src/cgal
        run: |
          cmake -B out -DCMAKE_BUILD_TYPE=Release
          cmake --build out --config Release
          cmake --install out --prefix install

      - name: Copy CGAL Install
        run: |
          mkdir -p dst/cgal
          cp -r src/cgal/install dst/cgal

      - name: Push Main
        working-directory: dst
        shell: bash
        run: |
          git config --global user.name "lemz1"
          git config --global user.email "${{ secrets.EMAIL }}"
          git add -A

          git fetch --all
          git pull --rebase

          if git diff --quiet; then
            echo "No changes to commit. Skipping push."
          else
            git commit -m "Workflow: Push Generated Binaries for ${{ matrix.os }}"
            git push
          fi
